### ISSUE TITLE
Policy data never change across all counties and time

### ISSUE THREAD

**Issue by zhaolongwen1990** [covid19datahub/COVID19#140]
I selected one-day data, all counties have the same restriction policy, which includes school_closing, workplace_place, gatherings_restriction, and all other restrictions in the package. Also, I selected one county which is Saint Louis county, it seems saint Louis county has a constant restriction policy across time this year which is impossible. I guess other counties have the same problem.

**Comment by eguidotti** [comment]
Hi @zhaolongwen1990, many thanks for your message! I just double checked.

As written [here](https://covid19datahub.io/articles/data.html) at the moment the policies for admin area 3 (i.e. counties) are inherited from national lavel policies. And from the  [Oxford Covid-19 Government Response Tracker](https://github.com/OxCGRT/covid-policy-tracker) it seems these national level policies have been the same since March (so basically since the case data for counties are available).

On the other hand, now that the policies for single states are available, it would be better to inherit the policies of counties from the corresponding state, and not the nation. I'll see how to fix this. Keep you posted!

**Comment by zhaolongwen1990** [comment]
Thanks for replying, Emanuele
This package is really important to our project, thanks for your work.
Where can I retrieve the single state policies? I don't see a related
command in the covid19 function.


covid19(
  country = NULL,
  level = 1,
  start = "2010-01-01",
  end = Sys.Date(),
  raw = FALSE,
  vintage = FALSE,
  verbose = TRUE,
  cache = TRUE,
  wb = NULL,
  gmr = NULL,
  amr = NULL
)

**Comment by eguidotti** [comment]
Hi @zhaolongwen1990, you can simply run the following to get the data (and policies) for the single US states:
```R
x <- covid19("USA", level = 2)
```
The policies are provided by [Oxford Covid-19 Government Response Tracker](https://github.com/OxCGRT/covid-policy-tracker).

I just committed the fix. In a few hours the dataset should include the policies for counties inherited by those of the corresponding state. Please let me know if this works for you or if you still see some issues with the data. 
Many thanks!

**Comment by zhaolongwen1990** [comment]
Now the covid19 package works perfectly, I can see how policies vary by
counties and time.
Appreciate your work!

Have a good weekend

**Comment by eguidotti** [comment]
Excellent! Thanks for confirming.
Have a nice weekend :)
