### ISSUE TITLE
U.S. data ? updating

### ISSUE THREAD

**Issue by kenshermock** [covid19datahub/COVID19#158]
I only leave this comment because we just resolved a situation where U.S. was not updating for several days. Normally by this time of day, level 3 U.S. data are updated over an hour ago. They are not updated as of now. And, because there is wide-spread alarm at the potential resurgence in the U.S., it is very important for me to have the most recent accurate data possible. Thank you and your team for your remarkable efforts.

**Comment by eguidotti** [comment]
Hi @kenshermock, I'm afraid I didn't understand your message.
I can see the US data level 3 up to date.  It may be that the update doesn't take place at the exact some time it did before. This is due to the increasing size of the data files and the longer times needed to aggregate the data. On 1st April we will stop to provide the pre-processed data files so to improve the maintainance of the raw data files. Also, the project is now supported by the R Consortium so to be sustainable in the years to come: https://www.r-consortium.org/blog/2020/12/14/r-consortium-providing-financial-support-to-covid-19-data-hub-platform

Please let me know if I can close the issue or if I'm missing something.
Thanks!
