### ISSUE TITLE
NY has no vaccination data

### ISSUE THREAD

**Issue by hlcny** [covid19datahub/COVID19#162]
In the US state-level data, vaccination is missing for New York. I don't know if this is intentional, but it is the only state with missing data.

**Comment by eguidotti** [comment]
Hi @hlcny, thanks for your message!
This is definitely not intentional. There was a wrong key for New York that is referenced as "New York State" by the data provider.
I should have fixed that and the data should be available in a couple of hours. 
Please let me know if this works for you and we can close this issue.
Thanks!

**Comment by eguidotti** [comment]
Seems fixed.
