### ISSUE TITLE
Inconsistent data for Germany?

### ISSUE THREAD

**Issue by sueskind** [covid19datahub/COVID19#167]
First of all, thanks to all contributors for this great project!

However, there seem to be some inconsistencies regarding the data for Germany. The confirmed cases are for the most part nearly equal to the recovered cases plus the deaths. This would mean that there were just a few active cases at one time.

Furthermore, the number of active cases is monotonically increasing which does not seem realistic.

Here is the code that I used to produce this:
```python
df, _ = covid19("DE")
df = df[["date", "confirmed", "recovered", "deaths"]].set_index("date")
df["active"] = df["confirmed"] - df["recovered"] - df["deaths"]
```

`df["active"]` is now very low at all times and only starts rising at the end.

Or am I misinterpreting the columns?

**Comment by eguidotti** [comment]
Hi @sueskind, thanks for your message.

Your interpretation of the columns is correct. You can find more info here https://covid19datahub.io/articles/doc/data.html

Regarding the data for Germany, we are pulling them from:
https://www.arcgis.com/home/item.html?id=f10774f1c63e40168479a1feb6c7ca74

You may want to reach out to them, as this issue seems to be related with the RKI data and unfortunately I'm not able to give precise information on their data collection methodology.

**Comment by sueskind** [comment]
Thank you @eguidotti for your response. I actually emailed the RKI before opening this issue, but they responded that they currently do not have the capacity to answer such questions.

The API documentation from them is quite confusing, too. Even for me, a native German speaker.

It would be great if you could leave this issue open for a while, maybe another contributor has a solution.

**Comment by eguidotti** [comment]
Ok, let's leave it open for a while.

**Comment by eguidotti** [comment]
It seems this has been inactive for a while. Hope you don't mind if I close it
