### ISSUE TITLE
Question to verify Israel hosp data

### ISSUE THREAD

**Issue by hlcny** [covid19datahub/COVID19#170]
Hi, I just wanted to verify the source and be sure there is no error in the Israel hospital data. The only documentation I found for Israel says it should be either from JHU or OWID. However, I don't believe JHU has hosp data and the data in covid19datahub does not match OWID (e.g., on 8/12 this source say 748, whereas OWID has 871 on that date--and 758 on 8/13...in  fact, none of the data here matches OWID exactly, though generally it is "close" so graphs look similar.
Thanks as always!

**Comment by eguidotti** [comment]
Hi @hlcny, the hospital data for Israel are from OWID. You can check it with:
```r
x <- covid19("ISR")
covid19cite(x)
```

It seems that OWID is updating the data retroactively (as done by many other sources due to the lag in reporting). Indeed, as of today I see 906 hospitalizations for 8/12 and 915 for 8/13. They do not match the numbers you observed 2 days ago but they are now the same in OWID and in this repository. 

The difference you observed between OWID and this repo may be due to a couple of hours of lag in updating the data hub with respect to the original update in OWID.

Here the link to the OWID dataset used:
- https://covid.ourworldindata.org/data/owid-covid-data.csv

Hope this helps!
