### ISSUE TITLE
Difference in state population at the state level, versus summing the counties

### ISSUE THREAD

**Issue by DonnKy** [covid19datahub/COVID19#185]
Thank you for this package. I have a question about state-level data for the US. For instance, I was examining New York State data For the date of filter ( date == "2021-12-09") 

> cv19_eoy %>% filter (county_fips == "36") %>% ## county_FIPS formerly from key_local
+   select (county_fips, state_name, county_name, population)  ## Formerly key_local, admin_area_level_2 and admin_area_level_3
# A tibble: 1 x 4
  county_fips state_name county_name population
  <chr>       <chr>      <chr>            <dbl>
1 36          New York   NA            **23628065**

> cv19_eoy %>% filter (str_sub(county_fips,1, 2) == "36") %>%
+   semi_join(tc_fips)  %>%
+   select (county_fips, state_name, county_name, population)  %>%
+   summarize (sum ( population), n())
Joining, by = c("state_name", "county_fips")
# A tibble: 1 x 2
  `sum(population)` `n()`
              <dbl> <int>
1          **19453561**    58
>

Thank you!

**Comment by eguidotti** [comment]
Hi @DonnKy, thanks for your message!
Population data for US if from JHU CSSE as listed [here](https://covid19datahub.io/reference/USA.html).
I re-checked and I see that they now list `19453561` instead of `23628065`. 
Maybe it was a mistake on my end. In any case, this is fixed now. You should get the correct population in a few hours.
I checked the other states and they look correct.
Let me know if you find anything else.
Many thanks!

**Comment by eguidotti** [comment]
I confirm this is now fixed. Thanks!

**Comment by DonnKy** [comment]
thank you so much for getting back to me so promptly. I am very much
enjoying this dataset
