### ISSUE TITLE
Differentiating cases from PCR and Rapid tests

### ISSUE THREAD

**Issue by M3IT** [covid19datahub/COVID19#196]
The Australian data currently provided records only cases confirmed by a HCP-administered PCR test. Data for self-administered and reported rapid tests are also available, but due to the less reliable nature of this data, isn't being included. 
Have you thought about providing additional columns in the data for RATs and total cases (PCR + RAT), or is the preference to provide the sum in the current confirmed cases column?

**Comment by eguidotti** [comment]
Hi @M3IT, thanks for your message!
Yes, I have been thinking about that some time ago... it's not an easy question. The problem is that different countries are counting confirmed cases differently. Some of them use only PCR confirmed cases, other countries use both PCR and RAT, other again started with PCR only and then included RAT... 

For this project I'm using the following convention (hope it makes sense!).
The goal is to have confirmation rates (`confirmed`/`tests`) homogeneous across countries. So if a country uses PCR confirmed cases, I report only the number of PCR for the `tests`. If a country uses both PCR and RAT confirmed cases, I report the sum of the two in the `tests`. Of course, there are countries that do not specify which tests are taken into account and/or do not provide data differentiating between PCR and RAT. So I'm forced to take the numbers they provide and put them in the `tests`.

So if Australia is providing PCR confirmed cases, then only PCR tests should be in `tests`

**Comment by eguidotti** [comment]
It seems this is fixed
