### ISSUE TITLE
In Iran: cumulative tests field has two issues

### ISSUE THREAD

**Issue by Marina-Antillon** [covid19datahub/COVID19#203]
1) In Iran the cumulative tests begin reporting much later (April 5, 2020) than cumulative cases (on Feb 19, 2020). If it is not possible to update the data with the tests taken from February 19 - April 5, then perhaps it can be noted in the documentation.
2) Cumulative tests sometimes have zeros after April 5, so if you want to calculate daily cases you need to interpolate first. I don't know if it's possible just for you to fill down or up or add a note to the documentation.

**Comment by eguidotti** [comment]
Thanks @Marina-Antillon! 

1. Unfortunately I don't know where to find cases and tests for Iran in early 2020. The data are now from JHU (cases) and Our World in Data (tests). 

2. It seems to me that there is no zero count for tests; they are missing data (`NA`).  In an early version of this project, we were providing a "pre-processed" dataset with the data already filled. But it didn't turn out to be a good choice. The reason is that interpolation is not trivial and a researcher may want to use one method or another depending on the use case. Dealing with missing data is left to the end user right now

Let me know if you have any other doubt or suggestion. Many thanks!

**Comment by Marina-Antillon** [comment]
Thanks! That makes sense.
