### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by guenterhack** [covid19datahub/COVID19#84]
First of all: Thank you very much for this fantastic project. I just wanted to know whether there are issues with the data updates or whether the update cycle has been extended to once a week instead of once a day. The last update on admin level 1 was on 2020-06-24, the last update on US admin level 3 on 2020-06-23. https://covid19datahub.io/articles/data.html

**Comment by eguidotti** [comment]
Hi @guenterhack, thank you so much for your message!
The data are updated hourly. 

It turned out to be an issue caused by the Slovenian data source that was causing the whole pipeline to fail. 
This is fixed now and you can get the latest data as usual.

You can also take advantage of high quality Australian and Japanese data by region thanks to the latest work in #77 and #83

Best,
-- Emanuele

**Comment by guenterhack** [comment]
Mille grazie, @emanuele-guidotti !
