### ISSUE TITLE
Proposal to rename the column "id" as "iso3c"

### ISSUE THREAD

**Issue by AndreaPi** [covid19datahub/COVID19#92]
Hi,

thanks for the excellent package! I have a minor suggestion - the `id` column is the ISO3C code for each country:

https://github.com/vincentarelbundock/countrycode

As a matter of fact, in other COVID datasets it's called `iso3c`:

https://joachim-gassen.github.io/2020/03/tidying-the-new-johns-hopkins-covid-19-datasests/

what about renaming it as `iso3c` in this package too? I think it would be a descriptive column name.

**Comment by eguidotti** [comment]
Hi @AndreaPi,
thank you for the suggestion but the `id` column will not be renamed.

The column corresponds to the iso code for the countries but is a hash for regions and cities. 
Since we aim at providing exactly the same data structure for data at national, regional or city level, we call that column `id`.
As a matter of fact, we store the ISO-3 code in the column named `iso_alpha_3`, which is the same of the column `id` only in case of national level data.

Best,
-- Emanuele
